version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true  # отключаем все линтеры по умолчанию
  enable:
    - govet
    - staticcheck
    # - errcheck  # закомментирован, но нужно явно отключить
    - unused
    - ineffassign
    - bodyclose
    - noctx
    - gocritic
    - prealloc
    - errorlint
    - nilerr
    - wrapcheck
 